describe('Event Detail Page', () => {

   it('Login_Email&Pass_correct', () => {
    /*Login เข้าสู่ระบบ */
    cy.visit('http://dekdee2.informatics.buu.ac.th:7111/login')
    cy.get('input[placeholder="Email"]')
      .type('admin@admin.com')
      .should('have.value', 'admin@admin.com')
    cy.get('input[placeholder="Password"]')
      .type('password')
      .should('have.value', 'password')
    cy.contains('button', 'Sign In').should('not.be.disabled').click()
    cy.url().should('not.include', '/login')

    /*ช่องค้นหา*/ 
    cy.visit('http://dekdee2.informatics.buu.ac.th:7111/event')
    cy.get('input[placeholder="Search event..."]')
      .should('be.visible')
      .type('งานเลี้ยงส่งท้ายปีเก่า')
      .should('have.value', 'งานเลี้ยงส่งท้ายปีเก่า')
    cy.get('button[aria-label="Search"]')
      .should('be.visible')
      .click()
    cy.wait(3000)
    cy.get('input[placeholder="Search event..."]')
      .clear()
      .should('have.value', '')
    cy.get('button[aria-label="Search"]')
      .should('be.visible')
      .click()
    cy.wait(3000)

    /**Filter */
    cy.contains('button', 'Filter')
    .should('be.visible')
    .click()

    cy.contains('label', 'All')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'All')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)
   
    cy.contains('label', 'ประชุม')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'ประชุม')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)
    
    cy.contains('label', 'สัมนา')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'สัมนา')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)

    cy.contains('label', 'อบรม')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'อบรม')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)

    cy.contains('label', 'Done')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'Done')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)

    cy.contains('label', 'Ongoing')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'Ongoing')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.wait(2000)

    cy.contains('label', 'Upcoming')
    .find('input')
    .check()
    .should('be.checked')
    cy.wait(2000)
    cy.contains('label', 'Upcoming')
    .find('input')
    .uncheck()
    .should('not.be.checked')

    cy.contains('button', 'Filter')
    .should('be.visible')
    .click()
  })
  
  })
